### ISSUE TITLE
Compatibility with style-elements

### ISSUE THREAD

**Issue by ghost** [doodledood/elm-split-pane#7]
I have been trying to get elm-split-pane to work with style-elements. 
https://github.com/mdgriffith/style-elements/tree/3.3.0

I inserted your nested example into a style-elements nested layout and while it works, it does exhibit some unexpected behavior.  When you drag the handle between panes it immediately jumps to about 90% of the panel width.  Drag again and it hits 100%.

I tried removing every option I could in both libraries to see if something specific was causing it.  I also poke around for a few hours in your code to see if I could figure anything out.

Just wondering from your perspective if anything comes to mind that may be an area to look at?

**Comment by doodledood** [comment]
Sounds to me like it might be related to the way width/height is
determined. Currently I use the parent height/width to scale and move the
splitter. You can start by trying to debug the width/height values
retrieved from parent (the mouse events and their mapping to an elm object )
