### ISSUE TITLE
Nested example question

### ISSUE THREAD

**Issue by ghost** [doodledood/elm-split-pane#8]
I have tried to created nested panes but seem to run into problems.  For example, if you use the nested example and simply change the vertical to horizontal ... meaning I would like three horizontal panes ... and you click on the far right pane, it will immediately collapse.   In fact, I am finding that behavior in about three different complex scenarios that I tried to create.

Here is an example: https://ellie-app.com/qgP4kpB5La1/0

If you drag the right splitter you can see the handle is way off the mouse and eventually it will just collapse.

**Comment by doodledood** [comment]
There was indeed a bug related to dragging the handle that caused this behavior. I pushed the fixes to master - can you confirm that it fixed the other three scenarios that you talked about too before I push an updated version to elm-package?

**Comment by ghost** [comment]
Unfortunately, I don't have all of those scenarios handy as they were iterative approaches to trying to get something to work.  But I am happy to report that I can confirm that the two scenarios I do have are now working as intended after the bug fix, which is awesome.  I really appreciate the quick response.

Also, one of the two scenarios included a simple 'elm-split-pane' inside a 'mdgriffith/style-elements' layout.  As I noted in a previous question, your library was not working in conjunction with style-elements.  As of this bug fix it seems to work fine!

I will start again this weekend with my original, more complex layout and report back.

**Comment by doodledood** [comment]
The new version should contain this fix as well. You can test the other scenarios if you want on the new version from elm-package.

**Comment by ghost** [comment]
Upgraded to 5.0.  This reported issue is now resolved.  Nesting 3 - 4 layers deep and so far no issues.
