### ISSUE TITLE
Percent vs Pixel

### ISSUE THREAD

**Issue by ghost** [doodledood/elm-split-pane#9]
Would it be possible to init a pane to a fixed width or height in pixels vs percent?

**Comment by doodledood** [comment]
Yeah sure, I have actually half implemented it already, I will finish and update soon :)

**Comment by ghost** [comment]
Thanks!

**Comment by doodledood** [comment]
Done :) I uploaded a new version to elm-package, but be aware that it contains a few breaking changes as I took the opportunity to simplify things a tiny bit to support it better. See the [nested example](https://github.com/doodledood/elm-split-pane/blob/master/examples/Nested.elm) for how to use it.

**Comment by ghost** [comment]
Yeah - not a problem.  Only took a few minutes to reconfigure for configureSplitter.  Thanks again.
